# Generated by Django 6.0.2 on 2026-02-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='summary',
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='avg_flowrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='avg_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='avg_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='total_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
