# Generated by Django 6.0.2 on 2026-02-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_uploadhistory_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='avg_flowrate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='avg_pressure',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='avg_temperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='total_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
